# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    # node.js
    - nodejs_version: 20

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g codecov

build: off

test_script:
  - node --version && npm --version
  - npm test

after_test:
  - codecov